export * as AuthSchema from './auth.schema'
export * as FitnessClassSchema from './fitnessClass.schema'
export * as ReviewSchema from './fitnessClassReview.schema'
export * as FavoriteClassSchema from './favoriteClass.schema'
export * as GymSchema from './gym.schema'
